apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: nginx-pod
      image: nginx
    - name: sidecar-pod
      image: almalinux
      Command: ["sleep, 200"]
# kubectl exec -it multi-pod -c sidecar-pod --bash
